[package]
name = "duskmourns-claim-sim"
description = "Simulating the deck built around Duskmourn's Claim (aka Parker Luck)."
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
mtg-lib-core.workspace = true
rand.workspace = true
